### ISSUE TITLE
[4.0.0] TypeError: Invalid Version: undefined

### ISSUE THREAD

**Issue by glensc** [masawada/yarn-outdated-formatter#78]
```
npm outdated --json --long | format-yarn-outdated.js
/Users/glen/scm/node/yarn-outdated-formatter/node_modules/semver/classes/semver.js:19
      throw new TypeError(`Invalid Version: ${version}`)
      ^

TypeError: Invalid Version: undefined
    at new SemVer (/Users/glen/scm/node/yarn-outdated-formatter/node_modules/semver/classes/semver.js:19:13)
    at Object.major (/Users/glen/scm/node/yarn-outdated-formatter/node_modules/semver/functions/major.js:2:29)
    at /Users/glen/scm/node/yarn-outdated-formatter/lib/Formatter.js:75:35
    at Array.forEach (<anonymous>)
    at Formatter.sortPackages (/Users/glen/scm/node/yarn-outdated-formatter/lib/Formatter.js:71:14)
    at Formatter.run (/Users/glen/scm/node/yarn-outdated-formatter/lib/Formatter.js:12:27)
    at Socket.<anonymous> (/Users/glen/scm/node/yarn-outdated-formatter/bin/format-yarn-outdated.js:68:37)
```

- [outdated-long.json](https://github.com/masawada/yarn-outdated-formatter/files/8192642/outdated-long.json.txt)

**Comment by masawada** [comment]
@glensc What version of npm are you using? There is no `current` parameter in that JSON, so `yarn-outdated-formatter` cannot determine the current version and an error occurs.

I tried in my local environment(`npm@8.3.1` in Node 16.14.0 and `npm@8.5.1` in Node 17.6.0), but no such JSON was output.

**Comment by masawada** [comment]
@glensc Reproduced when no dependencies are installed under the `node_modules` directory. Running `npm install` seems to solve the problem.
